[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "thermolib"
dynamic = ["version"]
requires-python = ">=3.10"

[tool.maturin]
bindings = "pyo3"
features = ["with_pyo3"]

